// DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
    // All changes done to this file will be lost upon re-running the 'silence createapi' command.
    // If you want to create new API methods, define them in a new file.

    'use_strict';
    
    import { BASE_URL, requestOptions } from './common.js';
    
    const departmentsAPI_auto ={

    /**
    * Gets all departments
    */
    getAll: function(){
    return new Promise (function (resolve, reject) 
    {
        axios
            .get(`${BASE_URL}/departments`,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Gets an entry from 'departments' by its primary key
    */
    getById: function(departmentId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .get(`${BASE_URL}/departments/${departmentId}`,requestOptions)
            .then(response => resolve(response.data[0]))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Creates a new entry in 'departments'
    */
    create: function(formData,){
    return new Promise (function (resolve, reject) 
    {
        axios
            .post(`${BASE_URL}/departments`,formData,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Updates an existing entry in 'departments' by its primary key
    */
    update: function(formData,departmentId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .put(`${BASE_URL}/departments/${departmentId}`,formData,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Deletes an existing entry in 'departments' by its primary key
    */
    delete: function(departmentId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .delete(`${BASE_URL}/departments/${departmentId}`,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },
};

export {departmentsAPI_auto};