// DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
    // All changes done to this file will be lost upon re-running the 'silence createapi' command.
    // If you want to create new API methods, define them in a new file.

    'use_strict';
    
    import { BASE_URL, requestOptions } from './common.js';
    
    const employeesAPI_auto ={

    /**
    * Gets all employees
    */
    getAll: function(){
    return new Promise (function (resolve, reject) 
    {
        axios
            .get(`${BASE_URL}/employees`,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Gets an entry from 'employees' by its primary key
    */
    getById: function(employeeId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .get(`${BASE_URL}/employees/${employeeId}`,requestOptions)
            .then(response => resolve(response.data[0]))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Creates a new entry in 'employees'
    */
    create: function(formData,){
    return new Promise (function (resolve, reject) 
    {
        axios
            .post(`${BASE_URL}/employees`,formData,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Updates an existing entry in 'employees' by its primary key
    */
    update: function(formData,employeeId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .put(`${BASE_URL}/employees/${employeeId}`,formData,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },

    /**
    * Deletes an existing entry in 'employees' by its primary key
    */
    delete: function(employeeId){
    return new Promise (function (resolve, reject) 
    {
        axios
            .delete(`${BASE_URL}/employees/${employeeId}`,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },
};

export {employeesAPI_auto};